
[package]
name = "animusd-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
thiserror = "2.0.17"
cajal-cx = { path = "/home/jordan/projs/cajal-framework/cajal-cx" }
serde = { version = "1.0.228", features = ["derive"] }

